name: Blockback
version: 1.2.0
main: us.ironcladnetwork.blockback.Blockback
api-version: '1.21'
load: POSTWORLD
authors: [ ClearPixels ]
description: Revert Path Blocks and Stripped Logs and Farmland
website: IroncladNetwork.us
commands:
  barkback:
    description: Toggle barkback functionality.
    usage: /barkback
    permission: blockback.bark

  pathback:
    description: Toggle pathback functionality.
    usage: /pathback
    permission: blockback.path

  farmback:
    description: Toggle farmback functionality.
    usage: /farmback
    permission: blockback.farm

  blockback:
    description: Main BlockBack command with reload functionality.
    usage: /blockback [reload]
    permission: blockback.use

permissions:
  blockback.bark:
    default: true
    description: Allows the player to toggle barkback.

  blockback.path:
    default: true
    description: Allows the player to toggle pathback.

  blockback.farm:
    default: true
    description: Allows the player to toggle farmback.

  blockback.use:
    default: true
    description: Allows the player to use the main blockback command.

  blockback.reload:
    default: op
    description: Allows the player to reload BlockBack configuration.
